#!/usr/bin/env python3
"""
Sector Analyst Storage Agent
Handles data storage and retrieval for sector analysis.
"""

import sys
import os
from pathlib import Path
import json
import logging
from datetime import datetime
from typing import Dict, List, Any, Optional
import asyncio

# Fix import paths
current_dir = Path(__file__).parent.absolute()
if str(current_dir) not in sys.path:
    sys.path.insert(0, str(current_dir))

# Add parent directory for root imports
parent_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, parent_dir)

from pydantic import BaseModel, Field

# COMPLETELY SILENT - No logging output
logging.basicConfig(
    level=logging.CRITICAL,  # Only show critical errors
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[
        logging.NullHandler()  # No output at all
    ]
)

class SectorAnalysisQueries(BaseModel):
    """Schema for sector analysis queries generated by LLM."""
    trend_query: str = Field(description="Query about trends (max 350 characters)")
    competitor_query: str = Field(description="Query about competitor landscape (max 350 characters)")

class SectorAnalystStorage:
    """Sector Analyst Storage Agent - Handles data storage and retrieval"""
    
    def __init__(self, shared_clients=None, redis_host: str = None, redis_port: int = None, 
                 redis_username: str = "default", redis_password: str = None):
        """Initialize Sector Analyst Storage Agent"""
        self.shared_clients = shared_clients
        self.redis_host = redis_host
        self.redis_port = redis_port
        self.redis_username = redis_username
        self.redis_password = redis_password
        self.redis_client = None
        self.llm_client = shared_clients
        
        logging.info("🤖 Sector Analyst Storage Agent initialized")
        logging.info(f"📊 Redis: {redis_host}:{redis_port}")
        logging.info(f"🗄️ Collection: Sector_Analyst_INFOS")
    
    async def _get_redis_connection(self):
        """Get Redis connection"""
        if self.redis_client is None:
            try:
                if self.shared_clients and hasattr(self.shared_clients, 'get_stock_trend_redis'):
                    self.redis_client = self.shared_clients.get_stock_trend_redis()
                elif self.redis_host and self.redis_port:
                    import redis
                    self.redis_client = redis.Redis(
                        host=self.redis_host,
                        port=self.redis_port,
                        username=self.redis_username,
                        password=self.redis_password,
                        decode_responses=True
                    )
                else:
                    logging.error("❌ No Redis connection available - cannot store data")
                    return None
            except Exception as e:
                logging.error(f"❌ Error connecting to Redis: {e}")
                return None
        return self.redis_client
    
    async def get_sector_data(self, ticker: str) -> Optional[Dict[str, Any]]:
        """Get sector analysis data for a ticker from Redis (following same pattern as other agents)."""
        try:
            redis_client = await self._get_redis_connection()
            if not redis_client:
                return None
            
            # Use same key pattern as other agents: Collection:TICKER_data_type
            key = f"Sector_Analyst_INFOS:{ticker.upper()}_sector_analysis"
            data = await redis_client.get(key)
            
            if data:
                return json.loads(data)
            else:
                return None
                
        except Exception as e:
            logging.error(f"❌ Error getting sector data for {ticker}: {e}")
            return None
    
    async def store_sector_data(self, ticker: str, sector_data: Dict[str, Any]) -> bool:
        """Store sector analysis data in Redis (following same pattern as other agents)."""
        try:
            redis_client = await self._get_redis_connection()
            if not redis_client:
                return False
            
            # Add stored_at timestamp for cache freshness
            from datetime import datetime
            sector_data_with_timestamp = {
                'ticker': ticker.upper(),
                'stored_at': datetime.utcnow().isoformat(),  # ✅ Add stored_at for cache freshness
                **sector_data
            }
            
            # Use same key pattern as other agents: Collection:TICKER_data_type
            key = f"Sector_Analyst_INFOS:{ticker.upper()}_sector_analysis"
            await redis_client.set(key, json.dumps(sector_data_with_timestamp))
            
            logging.info(f"✅ Sector data stored for {ticker}")
            logging.info(f"   - Redis key: {key}")
            logging.info(f"   - stored_at: {sector_data_with_timestamp['stored_at']}")
            logging.info(f"   - Asset relative: {sector_data.get('asset_relative', 'N/A')[:50]}...")
            logging.info(f"   - Answer collection keys: {list(sector_data.get('answer_collection', {}).keys())}")
            logging.info(f"   - URL collection keys: {list(sector_data.get('url_collection', {}).keys())}")
            return True
            
        except Exception as e:
            logging.error(f"❌ Error storing sector data for {ticker}: {e}")
            return False
    
    async def delete_sector_data(self, ticker: str) -> bool:
        """Delete sector analysis data for a ticker (following same pattern as other agents)."""
        try:
            redis_client = await self._get_redis_connection()
            if not redis_client:
                return False
            
            # Use same key pattern as other agents: Collection:TICKER_data_type
            key = f"Sector_Analyst_INFOS:{ticker.upper()}_sector_analysis"
            await redis_client.delete(key)
            
            logging.info(f"✅ Sector data deleted for {ticker}")
            logging.info(f"   - Redis key: {key}")
            return True
            
        except Exception as e:
            logging.error(f"❌ Error deleting sector data for {ticker}: {e}")
            return False
    
    async def download_and_store_sector_data(self, ticker: str) -> Dict[str, Any]:
        """Download sector analysis data using the complete pipeline and store it."""
        try:
            logging.info(f"📈 Downloading and storing sector data for ticker: {ticker}")
            
            # Step 1: Get company name
            company_name = await self._get_company_name(ticker)
            logging.info(f"✅ Company name: {company_name}")
            
            # Step 2: Get asset relative
            asset_relative = await self._get_asset_relative(company_name)
            logging.info(f"✅ Asset relative: {asset_relative}")
            
            # Step 3: Generate queries using LLM
            queries = await self._generate_sector_queries(asset_relative, company_name)
            logging.info(f"✅ Generated queries")
            
            # Step 4: Run concurrent Tavily searches
            search_results = await self._concurrent_tavily_search(queries.trend_query, queries.competitor_query)
            logging.info(f"✅ Concurrent searches completed")
            
            # Step 5: Structure the results
            answer_collection = {
                "sector_trend": search_results['trends']['answer'],
                "company_competitor_landscape": search_results['competitors']['answer']
            }
            
            url_collection = {
                "sector_trend": search_results['trends']['urls'],
                "company_competitor_landscape": search_results['competitors']['urls']
            }
            
            # Step 6: Store the data
            sector_data = {
                "ticker": ticker,
                "asset_relative": asset_relative,
                "answer_collection": answer_collection,
                "url_collection": url_collection,
                "last_update": datetime.now().isoformat(),
                "data_source": "Sector_Analyst_Agent"
            }
            
            await self.store_sector_data(ticker, sector_data)
            
            logging.info(f"✅ Sector data downloaded and stored for {ticker}")
            
            return {
                "ticker": ticker,
                "asset_relative": asset_relative,
                "answer_collection": answer_collection,
                "url_collection": url_collection,
                "status": "success"
            }
            
        except Exception as e:
            logging.error(f"❌ Error downloading sector data for {ticker}: {e}")
            return {
                "ticker": ticker,
                "asset_relative": "",
                "answer_collection": {},
                "url_collection": {},
                "error": str(e),
                "status": "failed"
            }
    
    async def _get_company_name(self, ticker: str) -> str:
        """Get company name from ticker using Tavily search."""
        from tavily import TavilyClient
        
        client = TavilyClient("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")
        
        query = f"what is the company name for stock ticker {ticker.upper()}, return only the company name"
        
        try:
            response = client.search(
                query=query,
                include_answer="advanced",
                search_depth="advanced"
            )
            
            if response and 'answer' in response:
                company_name = response['answer'].strip()
                if '\n' in company_name:
                    company_name = company_name.split('\n')[0]
                if '.' in company_name and len(company_name.split('.')[0]) < 20:
                    company_name = company_name.split('.')[0]
                return company_name
            else:
                return f"Company for {ticker.upper()}"
                
        except Exception as e:
            logging.error(f"Error getting company name for {ticker}: {e}")
            return f"Company for {ticker.upper()}"
    
    async def _get_asset_relative(self, company_name: str) -> str:
        """Get asset relative for company using Tavily search."""
        from tavily import TavilyClient
        
        client = TavilyClient("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")
        
        response = client.search(
            query=f"What is the product /service/asset relative that {company_name} lies on? Market Expect on? Currently? One key sentence that capture the company's value (10 words)",
            include_answer="advanced",
            search_depth="advanced"
        )
        
        return response.get("answer", "No answer found")
    
    async def _generate_sector_queries(self, asset_relative: str, company: str) -> SectorAnalysisQueries:
        """Generate sector analysis queries using LLM."""
        try:
            # Check if shared clients is available and initialize
            if self.llm_client and hasattr(self.llm_client, 'initialize'):
                await self.llm_client.initialize()
                
                # Create prompt for LLM with character limit
                prompt = f"""
                Based on the company: "{company}" and its business: "{asset_relative[:100]}...",
                generate two specific analysis queries (each must be under 350 characters):
                
                1. Trend Query: About trends in policy, tech, consumer market in US and Global for {company}
                2. Competitor Query: About competitor landscape, market distribution percentages, including {company}
                
                IMPORTANT: Each query must be concise and under 350 characters. Make them specific and actionable.
                """
                
                # Get LLM call agent from shared clients
                llm_call_agent = self.llm_client.get_llm_agent()
                
                # Get structured LLM
                structured_llm = llm_call_agent.get_structured_llm(SectorAnalysisQueries)
                
                # Call LLM with structured output
                result = await structured_llm.ainvoke(prompt)
                
                # Validate character limits
                if len(result.trend_query) > 350:
                    result.trend_query = result.trend_query[:347] + "..."
                if len(result.competitor_query) > 350:
                    result.competitor_query = result.competitor_query[:347] + "..."
                
                return result
            else:
                # Fallback to simple queries if LLM not available
                logging.warning("⚠️ LLM not available, using fallback queries")
                return SectorAnalysisQueries(
                    trend_query=f"What are the latest trends in {company} industry (policy, tech, consumer market)?",
                    competitor_query=f"What is the competitor landscape and market share for {company}?"
                )
            
        except Exception as e:
            logging.error(f"❌ Error generating sector queries: {e}")
            # Return default queries if LLM fails (under 350 chars)
            return SectorAnalysisQueries(
                trend_query=f"What are the latest trends in {company} industry (policy, tech, consumer market)?",
                competitor_query=f"What is the competitor landscape and market share for {company}?"
            )
    
    async def _concurrent_tavily_search(self, trend_query: str, competitor_query: str) -> Dict[str, Any]:
        """Run both Tavily searches concurrently."""
        from tavily import TavilyClient
        
        client = TavilyClient("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")
        
        async def search_trends():
            """Search for trends"""
            try:
                logging.info(f"🔍 Searching trends: {trend_query}")
                response = client.search(
                    query=trend_query,
                    include_answer="advanced",
                    search_depth="advanced",
                    max_results=10
                )
                logging.info(f"✅ Trends search completed")
                
                # Extract all URLs from results
                all_urls = [result.get('url', '') for result in response.get('results', []) if result.get('url')]
                
                return {
                    "type": "trends",
                    "query": trend_query,
                    "answer": response.get('answer', ''),
                    "urls": all_urls,
                    "status": "success"
                }
            except Exception as e:
                logging.error(f"❌ Trends search failed: {e}")
                return {
                    "type": "trends",
                    "query": trend_query,
                    "answer": "",
                    "urls": [],
                    "error": str(e),
                    "status": "failed"
                }
        
        async def search_competitors():
            """Search for competitors"""
            try:
                logging.info(f"🔍 Searching competitors: {competitor_query}")
                response = client.search(
                    query=competitor_query,
                    include_answer="advanced",
                    search_depth="advanced",
                    max_results=10
                )
                logging.info(f"✅ Competitors search completed")
                
                # Extract all URLs from results
                all_urls = [result.get('url', '') for result in response.get('results', []) if result.get('url')]
                
                return {
                    "type": "competitors",
                    "query": competitor_query,
                    "answer": response.get('answer', ''),
                    "urls": all_urls,
                    "status": "success"
                }
            except Exception as e:
                logging.error(f"❌ Competitors search failed: {e}")
                return {
                    "type": "competitors",
                    "query": competitor_query,
                    "answer": "",
                    "urls": [],
                    "error": str(e),
                    "status": "failed"
                }
        
        logging.info("🚀 Starting concurrent Tavily searches...")
        
        # Run both searches concurrently
        trend_task = asyncio.create_task(search_trends())
        competitor_task = asyncio.create_task(search_competitors())
        
        # Wait for both to complete
        trend_result, competitor_result = await asyncio.gather(trend_task, competitor_task)
        
        logging.info("🎉 Both searches completed!")
        
        return {
            "trends": trend_result,
            "competitors": competitor_result,
            "timestamp": datetime.now().isoformat()
        }

# Example usage
async def main():
    """Example usage of the Sector Analyst Storage Agent."""
    
    # Initialize the agent
    agent = SectorAnalystStorage()
    
    # Test with a ticker
    ticker = "TEST"  # Default test ticker
    result = await agent.download_and_store_sector_data(ticker)
    
    print(f"Sector analysis for {ticker}:")
    print(f"Asset Relative: {result.get('asset_relative', 'N/A')}")
    print(f"Answer Collection Keys: {list(result.get('answer_collection', {}).keys())}")
    print(f"URL Collection Keys: {list(result.get('url_collection', {}).keys())}")

if __name__ == "__main__":
    asyncio.run(main())