#!/usr/bin/env python3
"""
Sector Analyst Storage Agent
Handles data storage and retrieval for sector analysis.
"""

import sys
import os
from pathlib import Path
import json
import logging
from datetime import datetime
from typing import Dict, List, Any, Optional
import asyncio
import pandas as pd

# Fix import paths
current_dir = Path(__file__).parent.absolute()
if str(current_dir) not in sys.path:
    sys.path.insert(0, str(current_dir))

# Add parent directory for root imports
parent_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, parent_dir)

from pydantic import BaseModel, Field

# COMPLETELY SILENT - No logging output
logging.basicConfig(
    level=logging.CRITICAL,  # Only show critical errors
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[
        logging.NullHandler()  # No output at all
    ]
)

class SectorAnalysisQueries(BaseModel):
    """Schema for sector analysis queries generated by LLM."""
    trend_query: str = Field(description="Query about trends (max 350 characters)")
    competitor_query: str = Field(description="Query about competitor landscape (max 350 characters)")

class SectorIndexMatch(BaseModel):
    """Schema for sector index matching result."""
    ticker: str = Field(description="Matched ticker symbol")
    description: str = Field(description="Matched description")
    confidence_score: float = Field(description="Confidence score (0-1)")
    reasoning: str = Field(description="Reasoning for the match")

class SectorAnalystStorage:
    """Sector Analyst Storage Agent - Handles data storage and retrieval"""
    
    def __init__(self, shared_clients=None, redis_host: str = None, redis_port: int = None, 
                 redis_username: str = "default", redis_password: str = None):
        """
        Initialize Sector Analyst Storage Agent using centralized database_connection module
        
        Args:
            shared_clients: Shared clients instance (preferred)
            redis_host: Redis host (deprecated - use shared_clients)
            redis_port: Redis port (deprecated - use shared_clients)
            redis_username: Redis username (deprecated - use shared_clients)
            redis_password: Redis password (deprecated - use shared_clients)
        """
        # Import centralized database connection
        import sys
        import os
        backend_dir = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
        if backend_dir not in sys.path:
            sys.path.insert(0, backend_dir)
        
        from Source_File.database_connection import RedisDatabaseStorage as CentralizedStorage
        
        # Use centralized storage for connection management
        if shared_clients:
            # Use shared connection pool (preferred)
            self.db_storage = CentralizedStorage(db_type="stock_trend", shared_clients=shared_clients)
            logging.info("✅ Using shared stock trend Redis connection via database_connection")
        else:
            # Fallback to direct connection (but still use database_connection)
            self.db_storage = CentralizedStorage(db_type="stock_trend", shared_clients=None)
            logging.info("✅ Using direct stock trend Redis connection via database_connection")
        
        # Expose client for backward compatibility
        self.redis_client = None  # Will be set lazily when needed
        self.shared_clients = shared_clients
        self.llm_client = shared_clients
        
        # Load sector index data
        self.sector_index_df = self._load_sector_index_data()
        
        logging.info("🤖 Sector Analyst Storage Agent initialized")
        logging.info(f"📊 Redis: Connected via database_connection")
        logging.info(f"🗄️ Collection: Sector_Analyst_INFOS")
        logging.info(f"📈 Sector indices loaded: {len(self.sector_index_df)} entries")
    
    def _load_sector_index_data(self) -> pd.DataFrame:
        """Load sector index data from CSV file."""
        try:
            # Get the path to the CSV file in the same directory
            csv_path = Path(__file__).parent / "sector_index_tickers.csv"
            print(f"🔍 Loading sector index CSV from: {csv_path}")
            
            if csv_path.exists():
                print(f"✅ CSV file exists, loading...")
                df = pd.read_csv(csv_path)
                print(f"   Loaded {len(df)} rows, columns: {list(df.columns)}")
                
                # Ensure we have the expected columns
                if 'Ticker' in df.columns and 'Description' in df.columns:
                    print(f"✅ Loaded {len(df)} sector indices from CSV")
                    print(f"   Sample tickers: {list(df['Ticker'].head())}")
                    return df
                else:
                    print(f"⚠️ CSV missing expected columns. Found: {list(df.columns)}")
                    return pd.DataFrame(columns=['Ticker', 'Description'])
            else:
                print(f"⚠️ Sector index CSV not found at: {csv_path}")
                return pd.DataFrame(columns=['Ticker', 'Description'])
                
        except Exception as e:
            print(f"❌ Error loading sector index data: {e}")
            import traceback
            print(f"   Traceback: {traceback.format_exc()}")
            return pd.DataFrame(columns=['Ticker', 'Description'])
    
    async def _match_sector_index(self, asset_relative: str, company_name: str) -> Optional[Dict[str, Any]]:
        """Match the best sector index using LLM analysis."""
        try:
            print(f"🔍 Matching sector index for {company_name}")
            print(f"   Available sector indices: {len(self.sector_index_df)} entries")
            
            if self.sector_index_df.empty:
                print("⚠️ No sector index data available for matching")
                return None
            
            # Prepare context for LLM
            sector_options = []
            for _, row in self.sector_index_df.iterrows():
                sector_options.append(f"Ticker: {row['Ticker']}, Description: {row['Description']}")
            
            sector_options_text = "\n".join(sector_options)
            
            # Create prompt for LLM
            prompt = f"""
            Based on the company "{company_name}" and its business description "{asset_relative}",
            select the most appropriate sector index from the following options:
            
            {sector_options_text}
            
            Analyze the company's business model, industry sector, and market exposure to determine the best match.
            Consider factors like:
            - Primary business sector (technology, healthcare, financial, etc.)
            - Market cap category (large cap, mid cap, small cap)
            - Geographic exposure
            - Industry-specific indices vs broad market indices
            
            **COMPREHENSIVE SECTOR MAPPING GUIDELINES:**
            
            **CRYPTO/BLOCKCHAIN COMPANIES:**
            - Stablecoin issuers (USDC, USDT, DAI): BTC-USD, ETH-USD
            - Crypto exchanges (Coinbase, Binance): BTC-USD, ETH-USD
            - Blockchain infrastructure providers: BTC-USD, ETH-USD
            - Bitcoin/crypto mining companies: BTC-USD
            - Digital currency/crypto companies: BTC-USD, ETH-USD
            
            **US SECTOR-SPECIFIC ETFs:**
            - Technology: XLK (Technology Select Sector SPDR Fund)
            - Financial Services: XLF (Financial Select Sector SPDR Fund)
            - Energy: XLE (Energy Select Sector SPDR Fund)
            - Healthcare: XLV (Health Care Select Sector SPDR Fund)
            - Consumer Discretionary: XLY (Consumer Discretionary Select Sector SPDR Fund)
            - Consumer Staples: XLP (Consumer Staples Select Sector SPDR Fund)
            - Industrial: XLI (Industrial Select Sector SPDR Fund)
            - Materials: XLB (Materials Select Sector SPDR Fund)
            - Real Estate: XLRE (Real Estate Select Sector SPDR Fund)
            - Utilities: XLU (Utilities Select Sector SPDR Fund)
            - Communication Services: XLC (Communication Services Select Sector SPDR Fund)
            
            **SEMICONDUCTOR COMPANIES:**
            - Semiconductor manufacturers: ^SOX, SMH, SOXX
            - Chip design companies: ^SOX, SMH, SOXX
            
            **US BROAD MARKET INDICES:**
            - Large-cap diversified: SPY, ^GSPC, DIA
            - Tech-heavy large-cap: QQQ, ^IXIC
            - Volatility/risk measurement: ^VIX
            
            **EUROPEAN COMPANIES:**
            - Pan-European: ^STOXX50E, ^STOXX, FEZ, VGK, IEUR
            - Germany: ^GDAXI, EWG
            - France: ^FCHI, EWQ
            - UK: ^FTSE, EWU
            - Spain: ^IBEX, EWP
            - Italy: FTSEMIB.MI, EWI
            - Switzerland: ^SSMI, EWL
            - Netherlands: ^AEX, EWN
            - Sweden: ^OMXS30, EWD
            - Poland: EPOL
            - Greece: GREK
            - Ireland: EIRL
            
            **ASIAN COMPANIES:**
            - Japan: ^N225, ^TOPX, EWJ
            - Hong Kong: ^HSI, EWH
            - China: ^SSEC, 000300.SS, MCHI, FXI
            - Hong Kong China Tech: ^HSTECH
            - South Korea: ^KS11, EWY
            - Taiwan: ^TWII, EWT
            - India: ^NSEI, ^BSESN, INDA
            - Australia: ^AXJO, EWA
            - New Zealand: ^NZ50
            - Singapore: EWS
            - Malaysia: EWM
            - Indonesia: EIDO
            - Turkey: TUR
            
            **AMERICAS (NON-US):**
            - Canada: ^GSPTSE, EWC
            - Brazil: ^BVSP, EWZ
            - Mexico: ^MXX, EWW
            - Argentina: ARGT
            - Peru: EPU
            - Chile: ECH
            
            **GLOBAL/EMERGING MARKETS:**
            - All Country World: ACWI
            - Developed Markets: VEA, EFA
            - Emerging Markets: VWO, EEM
            
            **CURRENCY/FOREX:**
            - USD strength: DX-Y.NYB
            - Major pairs: EURUSD=X, USDJPY=X, USDCNY=X, USDCNH=X, GBPUSD=X, USDCHF=X, USDCAD=X
            
            Return the best match with a confidence score and reasoning.
            """
            
            # Check if shared clients is available and initialize
            print(f"   Checking LLM client availability...")
            if self.llm_client and hasattr(self.llm_client, 'initialize'):
                print(f"   Initializing LLM client...")
                await self.llm_client.initialize()
                
                # Get LLM call agent from shared clients
                print(f"   Getting LLM call agent...")
                llm_call_agent = self.llm_client.get_llm_agent()
                
                # Get structured LLM
                print(f"   Getting structured LLM...")
                structured_llm = llm_call_agent.get_structured_llm(SectorIndexMatch)
                
                # Call LLM with structured output
                print(f"   Calling LLM for sector matching...")
                result = await structured_llm.ainvoke(prompt)
                print(f"   LLM result: {result}")
                
                # Validate the result
                if result.ticker in self.sector_index_df['Ticker'].values:
                    logging.info(f"✅ Sector index matched: {result.ticker} - {result.description}")
                    logging.info(f"   Confidence: {result.confidence_score:.2f}")
                    logging.info(f"   Reasoning: {result.reasoning}")
                    
                    return {
                        "ticker": result.ticker,
                        "description": result.description,
                        "confidence_score": result.confidence_score,
                        "reasoning": result.reasoning,
                        "match_method": "llm_analysis"
                    }
                else:
                    print(f"⚠️ LLM returned invalid ticker: {result.ticker}")
                    print(f"   Available tickers: {list(self.sector_index_df['Ticker'].values)}")
                    return None
            else:
                print(f"⚠️ LLM not available for sector index matching")
                print(f"   LLM client: {self.llm_client}")
                print(f"   Has initialize: {hasattr(self.llm_client, 'initialize') if self.llm_client else 'No client'}")
                return None
                
        except Exception as e:
            print(f"❌ Error matching sector index: {e}")
            import traceback
            print(f"   Traceback: {traceback.format_exc()}")
            return None
    
    def get_sector_index_data(self) -> pd.DataFrame:
        """Get the loaded sector index data for external use."""
        return self.sector_index_df.copy()
    
    def reload_sector_index_data(self) -> bool:
        """Reload sector index data from CSV file."""
        try:
            self.sector_index_df = self._load_sector_index_data()
            logging.info(f"✅ Reloaded sector index data: {len(self.sector_index_df)} entries")
            return True
        except Exception as e:
            logging.error(f"❌ Error reloading sector index data: {e}")
            return False
    
    def _get_redis_connection(self):
        """Get Redis connection (using database_connection module)."""
        if not self.redis_client:
            # Use the centralized storage client
            self.redis_client = self.db_storage.redis_client
        return self.redis_client
    
    def _is_async_redis(self, client) -> bool:
        """Check if Redis client is async (aioredis)"""
        return hasattr(client, '__class__') and 'aioredis' in str(type(client))
    
    async def get_sector_data(self, ticker: str) -> Optional[Dict[str, Any]]:
        """Get sector analysis data for a ticker from Redis (following same pattern as other agents)."""
        try:
            redis_client = self._get_redis_connection()
            if not redis_client:
                return None
            
            # Use same key pattern as other agents: Collection:TICKER_data_type
            key = f"Sector_Analyst_INFOS:{ticker.upper()}_sector_analysis"
            
            # Handle both sync and async Redis clients
            is_async = self._is_async_redis(redis_client)
            if is_async:
                data = await redis_client.get(key)
            else:
                data = redis_client.get(key)
            
            if data:
                return json.loads(data)
            else:
                return None
                
        except Exception as e:
            logging.error(f"❌ Error getting sector data for {ticker}: {e}")
            return None
    
    async def store_sector_data(self, ticker: str, sector_data: Dict[str, Any]) -> bool:
        """Store sector analysis data in Redis (following same pattern as other agents)."""
        try:
            redis_client = self._get_redis_connection()
            if not redis_client:
                return False
            
            # Add stored_at timestamp for cache freshness
            from datetime import datetime
            sector_data_with_timestamp = {
                'ticker': ticker.upper(),
                'stored_at': datetime.utcnow().isoformat(),  # ✅ Add stored_at for cache freshness
                **sector_data
            }
            
            # Use same key pattern as other agents: Collection:TICKER_data_type
            key = f"Sector_Analyst_INFOS:{ticker.upper()}_sector_analysis"
            
            # Handle both sync and async Redis clients
            is_async = self._is_async_redis(redis_client)
            if is_async:
                await redis_client.set(key, json.dumps(sector_data_with_timestamp))
            else:
                redis_client.set(key, json.dumps(sector_data_with_timestamp))
            
            logging.info(f"✅ Sector data stored for {ticker}")
            logging.info(f"   - Redis key: {key}")
            logging.info(f"   - stored_at: {sector_data_with_timestamp['stored_at']}")
            logging.info(f"   - Asset relative: {sector_data.get('asset_relative', 'N/A')[:50]}...")
            logging.info(f"   - Answer collection keys: {list(sector_data.get('answer_collection', {}).keys())}")
            logging.info(f"   - URL collection keys: {list(sector_data.get('url_collection', {}).keys())}")
            return True
            
        except Exception as e:
            logging.error(f"❌ Error storing sector data for {ticker}: {e}")
            return False
    
    async def delete_sector_data(self, ticker: str) -> bool:
        """Delete sector analysis data for a ticker (following same pattern as other agents)."""
        try:
            redis_client = self._get_redis_connection()
            if not redis_client:
                return False
            
            # Use same key pattern as other agents: Collection:TICKER_data_type
            key = f"Sector_Analyst_INFOS:{ticker.upper()}_sector_analysis"
            
            # Handle both sync and async Redis clients
            is_async = self._is_async_redis(redis_client)
            if is_async:
                await redis_client.delete(key)
            else:
                redis_client.delete(key)
            
            logging.info(f"✅ Sector data deleted for {ticker}")
            logging.info(f"   - Redis key: {key}")
            return True
            
        except Exception as e:
            logging.error(f"❌ Error deleting sector data for {ticker}: {e}")
            return False
    
    async def download_and_store_sector_data(self, ticker: str) -> Dict[str, Any]:
        """Download sector analysis data using the complete pipeline and store it."""
        try:
            logging.info(f"📈 Downloading and storing sector data for ticker: {ticker}")
            
            # Step 1: Get company name
            company_name = await self._get_company_name(ticker)
            logging.info(f"✅ Company name: {company_name}")
            
            # Step 2: Get asset relative
            asset_relative = await self._get_asset_relative(company_name)
            logging.info(f"✅ Asset relative: {asset_relative}")
            
            # Step 2.5: Extract 1-5 word sector summary using LLM
            sector_summary = await self._extract_sector_summary(asset_relative, company_name)
            logging.info(f"✅ Sector summary: '{sector_summary}'")
            
            # Step 2.75: Match sector index using LLM
            sector_index_match = await self._match_sector_index(asset_relative, company_name)
            logging.info(f"✅ Sector index matching completed")
            
            # Step 3: Generate queries using LLM
            queries = await self._generate_sector_queries(asset_relative, company_name)
            logging.info(f"✅ Generated queries")
            
            # Step 4: Run concurrent Tavily searches
            search_results = await self._concurrent_tavily_search(queries.trend_query, queries.competitor_query)
            logging.info(f"✅ Concurrent searches completed")
            
            # Step 5: Structure the results
            answer_collection = {
                "sector_trend": search_results['trends']['answer'],
                "company_competitor_landscape": search_results['competitors']['answer']
            }
            
            url_collection = {
                "sector_trend": search_results['trends']['urls'],
                "company_competitor_landscape": search_results['competitors']['urls']
            }
            
            # Step 5.5: Extract competitor summary using LLM
            competitor_summary = await self._extract_competitor_summary(
                asset_relative, 
                answer_collection.get('company_competitor_landscape', ''),
                company_name
            )
            logging.info(f"✅ Competitor summary: '{competitor_summary}'")
            
            # Step 6: Store the data
            sector_data = {
                "ticker": ticker,
                "asset_relative": asset_relative,
                "asset_relative_summary": sector_summary,  # NEW: 1-5 word sector summary
                "competitor_summary": competitor_summary,  # NEW: Comma-separated competitor names
                "relative_sector_index": sector_index_match,
                "answer_collection": answer_collection,
                "url_collection": url_collection,
                "last_update": datetime.now().isoformat(),
                "data_source": "Sector_Analyst_Agent"
            }
            
            await self.store_sector_data(ticker, sector_data)
            
            logging.info(f"✅ Sector data downloaded and stored for {ticker}")
            
            return {
                "ticker": ticker,
                "asset_relative": asset_relative,
                "asset_relative_summary": sector_summary,  # NEW: 1-5 word sector summary
                "competitor_summary": competitor_summary,  # NEW: Comma-separated competitor names
                "relative_sector_index": sector_index_match,
                "answer_collection": answer_collection,
                "url_collection": url_collection,
                "status": "success"
            }
            
        except Exception as e:
            logging.error(f"❌ Error downloading sector data for {ticker}: {e}")
            return {
                "ticker": ticker,
                "asset_relative": "",
                "asset_relative_summary": "",
                "competitor_summary": "",
                "relative_sector_index": None,
                "answer_collection": {},
                "url_collection": {},
                "error": str(e),
                "status": "failed"
            }
    
    async def _get_company_name(self, ticker: str) -> str:
        """Get company name from ticker using Tavily search."""
        from tavily import TavilyClient
        
        client = TavilyClient("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")
        
        query = f"what is the company name for stock ticker {ticker.upper()}, return only the company name"
        
        try:
            response = client.search(
                query=query,
                include_answer="advanced",
                search_depth="advanced"
            )
            
            if response and 'answer' in response:
                company_name = response['answer'].strip()
                if '\n' in company_name:
                    company_name = company_name.split('\n')[0]
                if '.' in company_name and len(company_name.split('.')[0]) < 20:
                    company_name = company_name.split('.')[0]
                return company_name
            else:
                return f"Company for {ticker.upper()}"
                
        except Exception as e:
            logging.error(f"Error getting company name for {ticker}: {e}")
            return f"Company for {ticker.upper()}"
    
    async def _get_asset_relative(self, company_name: str) -> str:
        """Get asset relative for company using Tavily search."""
        from tavily import TavilyClient
        
        client = TavilyClient("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")
        
        response = client.search(
            query=f"What is the product /service/asset relative that {company_name} lies on? Market Expect on? Currently? One key sentence that capture the company's value (10 words)",
            include_answer="advanced",
            search_depth="advanced"
        )
        
        return response.get("answer", "No answer found")
    
    async def _extract_sector_summary(self, asset_relative: str, company_name: str) -> str:
        """
        Extract 1-5 word sector summary from asset_relative description using LLM.
        
        Args:
            asset_relative: Long description of company's business
            company_name: Company name for context
        
        Returns:
            1-5 word sector name (e.g., "Retail", "AI Cloud Infrastructure", "Electric Vehicles")
        """
        try:
            # Get LLM agent
            if self.llm_client:
                llm_call_agent = self.llm_client.get_llm_agent()
            else:
                from LLM_Call_Agent import LLMCallAgent
                llm_call_agent = LLMCallAgent(
                    default_provider="deepseek",
                    default_model="deepseek-chat"
                )
            
            # Create prompt for 1-5 word sector extraction
            prompt = f"""Extract a 1-5 word sector/industry name from this company description:

Company: {company_name}
Description: {asset_relative}

Requirements:
- Must be 1-5 words only
- Describe the core business/sector/industry
- Be specific and clear
- Use standard industry terms

Examples:
- "general merchandise retailer competing with Walmart" → "Retail"
- "AI cloud-computing company providing GPU infrastructure" → "AI Cloud Infrastructure"
- "electric vehicle manufacturer" → "Electric Vehicles"
- "stablecoin issuer blockchain payments" → "Cryptocurrency"
- "semiconductor chip design" → "Semiconductors"
- "social media platform" → "Social Media"
- "pharmaceutical drug development" → "Pharmaceuticals"
- "commercial aerospace manufacturing" → "Aerospace"

Return ONLY the 1-5 word sector name, nothing else. No explanation, no punctuation."""

            # Call LLM
            sector_summary = llm_call_agent.call_deepseek(prompt)
            
            # Clean and validate
            sector_summary = sector_summary.strip().strip('"').strip("'")
            
            # Count words
            word_count = len(sector_summary.split())
            
            if word_count > 5:
                # Too long, take first 5 words
                sector_summary = ' '.join(sector_summary.split()[:5])
                logging.warning(f"⚠️ Sector summary too long ({word_count} words), truncated to: {sector_summary}")
            
            logging.info(f"✅ Extracted sector summary: '{sector_summary}' ({len(sector_summary.split())} words)")
            
            return sector_summary
            
        except Exception as e:
            logging.error(f"❌ Error extracting sector summary: {e}")
            # Fallback: Use relative_sector_index description if available
            return "Unknown Sector"
    
    async def _extract_competitor_summary(self, asset_relative: str, competitor_landscape: str, company_name: str) -> str:
        """
        Extract competitor names from competitor landscape text using LLM.
        
        Args:
            asset_relative: Company description (contains competitor info)
            competitor_landscape: Detailed competitor analysis text (may be null)
            company_name: Company name for context
        
        Returns:
            Comma-separated competitor names (e.g., "Walmart, Amazon, Costco, Best Buy")
        """
        try:
            # Get LLM agent
            if self.llm_client:
                llm_call_agent = self.llm_client.get_llm_agent()
            else:
                from LLM_Call_Agent import LLMCallAgent
                llm_call_agent = LLMCallAgent(
                    default_provider="deepseek",
                    default_model="deepseek-chat"
                )
            
            # Use competitor_landscape if available, otherwise use asset_relative
            if competitor_landscape and competitor_landscape.strip():
                source_text = competitor_landscape[:1500]  # Use more context if available
            else:
                source_text = asset_relative[:1000]
            
            # Create prompt for competitor extraction
            prompt = f"""Extract the main competitor names from this text:

Company: {company_name}
Text: {source_text}

Requirements:
- Extract 1-4 competitor company names
- Return ONLY company names, separated by commas
- Use short company names (e.g., "Walmart" not "Walmart Inc.")
- Order by importance/mention frequency
- If no competitors found, return "None"

Examples:
- "competing with Walmart, Amazon, and Costco" → "Walmart, Amazon, Costco"
- "rivals include AWS, Microsoft Azure, Google Cloud" → "AWS, Microsoft Azure, Google Cloud"
- "major players like Tesla, Rivian, and Lucid" → "Tesla, Rivian, Lucid"

Return ONLY comma-separated names, nothing else. Format: "Competitor1, Competitor2, Competitor3"."""

            # Call LLM
            competitor_summary = llm_call_agent.call_deepseek(prompt)
            
            # Clean and validate
            competitor_summary = competitor_summary.strip().strip('"').strip("'")
            
            # Check if no competitors found
            if competitor_summary.lower() in ['none', 'no competitors', 'n/a']:
                logging.info(f"ℹ️ No competitors found for {company_name}")
                return "None"
            
            # Split and limit to 4 competitors
            competitors = [c.strip() for c in competitor_summary.split(',')]
            if len(competitors) > 4:
                competitors = competitors[:4]
                competitor_summary = ', '.join(competitors)
                logging.warning(f"⚠️ Too many competitors ({len(competitors)}), limited to 4")
            
            logging.info(f"✅ Extracted competitors: '{competitor_summary}' ({len(competitors)} competitors)")
            
            return competitor_summary
            
        except Exception as e:
            logging.error(f"❌ Error extracting competitor summary: {e}")
            return "None"
    
    async def _generate_sector_queries(self, asset_relative: str, company: str) -> SectorAnalysisQueries:
        """Generate sector analysis queries using LLM."""
        try:
            # Check if shared clients is available and initialize
            if self.llm_client and hasattr(self.llm_client, 'initialize'):
                await self.llm_client.initialize()
                
                # Create prompt for LLM with character limit
                prompt = f"""
                Based on the company: "{company}" and its business: "{asset_relative[:100]}...",
                generate two specific analysis queries (each must be under 350 characters):
                
                1. Trend Query: About trends in policy, tech, consumer market in US and Global for {company}
                2. Competitor Query: Competitor landscape and market share for {company}, include all relative competitors (existing top players, potential emerging rivals, and struggling competitors)
                
                IMPORTANT: Each query must be concise and under 350 characters. Make them specific and actionable.
                """
                
                # Get LLM call agent from shared clients
                llm_call_agent = self.llm_client.get_llm_agent()
                
                # Get structured LLM
                structured_llm = llm_call_agent.get_structured_llm(SectorAnalysisQueries)
                
                # Call LLM with structured output
                result = await structured_llm.ainvoke(prompt)
                
                # Validate character limits
                if len(result.trend_query) > 350:
                    result.trend_query = result.trend_query[:347] + "..."
                if len(result.competitor_query) > 350:
                    result.competitor_query = result.competitor_query[:347] + "..."
                
                return result
            else:
                # Fallback to simple queries if LLM not available
                logging.warning("⚠️ LLM not available, using fallback queries")
                return SectorAnalysisQueries(
                    trend_query=f"What are the latest trends in {company} industry (policy, tech, consumer market)?",
                    competitor_query=f"Competitor landscape and market share for {company}, include all relative competitors (top players, emerging rivals, struggling competitors)"
                )
            
        except Exception as e:
            logging.error(f"❌ Error generating sector queries: {e}")
            # Return default queries if LLM fails (under 350 chars)
            return SectorAnalysisQueries(
                trend_query=f"What are the latest trends in {company} industry (policy, tech, consumer market)?",
                competitor_query=f"Competitor landscape and market share for {company}, include all relative competitors (top players, emerging rivals, struggling competitors)"
            )
    
    async def _concurrent_tavily_search(self, trend_query: str, competitor_query: str) -> Dict[str, Any]:
        """Run both Tavily searches concurrently."""
        from tavily import TavilyClient
        
        client = TavilyClient("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")
        
        async def search_trends():
            """Search for trends"""
            try:
                logging.info(f"🔍 Searching trends: {trend_query}")
                response = client.search(
                    query=trend_query,
                    include_answer="advanced",
                    search_depth="advanced",
                    max_results=10
                )
                logging.info(f"✅ Trends search completed")
                
                # Extract all URLs from results
                all_urls = [result.get('url', '') for result in response.get('results', []) if result.get('url')]
                
                return {
                    "type": "trends",
                    "query": trend_query,
                    "answer": response.get('answer', ''),
                    "urls": all_urls,
                    "status": "success"
                }
            except Exception as e:
                logging.error(f"❌ Trends search failed: {e}")
                return {
                    "type": "trends",
                    "query": trend_query,
                    "answer": "",
                    "urls": [],
                    "error": str(e),
                    "status": "failed"
                }
        
        async def search_competitors():
            """Search for competitors"""
            try:
                logging.info(f"🔍 Searching competitors: {competitor_query}")
                response = client.search(
                    query=competitor_query,
                    include_answer="advanced",
                    search_depth="advanced",
                    max_results=10
                )
                logging.info(f"✅ Competitors search completed")
                
                # Extract all URLs from results
                all_urls = [result.get('url', '') for result in response.get('results', []) if result.get('url')]
                
                return {
                    "type": "competitors",
                    "query": competitor_query,
                    "answer": response.get('answer', ''),
                    "urls": all_urls,
                    "status": "success"
                }
            except Exception as e:
                logging.error(f"❌ Competitors search failed: {e}")
                return {
                    "type": "competitors",
                    "query": competitor_query,
                    "answer": "",
                    "urls": [],
                    "error": str(e),
                    "status": "failed"
                }
        
        logging.info("🚀 Starting concurrent Tavily searches...")
        
        # Run both searches concurrently
        trend_task = asyncio.create_task(search_trends())
        competitor_task = asyncio.create_task(search_competitors())
        
        # Wait for both to complete
        trend_result, competitor_result = await asyncio.gather(trend_task, competitor_task)
        
        logging.info("🎉 Both searches completed!")
        
        return {
            "trends": trend_result,
            "competitors": competitor_result,
            "timestamp": datetime.now().isoformat()
        }

# Example usage
async def main():
    """Example usage of the Sector Analyst Storage Agent."""
    
    # Initialize the agent
    agent = SectorAnalystStorage()
    
    # Test with a ticker
    ticker = "TEST"  # Default test ticker
    result = await agent.download_and_store_sector_data(ticker)
    
    print(f"Sector analysis for {ticker}:")
    print(f"Asset Relative: {result.get('asset_relative', 'N/A')}")
    print(f"Answer Collection Keys: {list(result.get('answer_collection', {}).keys())}")
    print(f"URL Collection Keys: {list(result.get('url_collection', {}).keys())}")
    
    # NEW: Show sector index match
    sector_index = result.get('relative_sector_index', {})
    if sector_index:
        print(f"Sector Index Match: {sector_index.get('ticker', 'N/A')} - {sector_index.get('description', 'N/A')}")
        print(f"Confidence Score: {sector_index.get('confidence_score', 'N/A')}")
        print(f"Reasoning: {sector_index.get('reasoning', 'N/A')}")
    else:
        print("Sector Index Match: No match found")

if __name__ == "__main__":
    asyncio.run(main())